version: '2'
services:
  nginx-web-files:
    image: registry.cn-shanghai.aliyuncs.com/jrdn/nginx-web-files:0.0.1
    container_name: web-files
    ports:
      - "80:80"
      - "443:443"
    networks:
      - "netNameBankHh"
#    volumes:
##      - /opt/jrdn/nginx_bank/logs:/var/log/nginx
#      - /opt/jrdn/web-files:/data/web
    restart: always
networks:
  netNameBankHh:
    driver: bridge
